import { addMission, getMissions } from "@/application/useCases/campaign";
import { repositories } from "@/infrastructure/config/repositories";
import { embeddedMissionSchema } from "@/infrastructure/adapters/schemas/campaign.schema";
import { NextRequest, NextResponse } from "next/server";

/**
 * GET /api/campaign/[id]/missions
 * Returns all missions for a campaign
 */
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const campaignId = (await params).id;
    const missions = await getMissions(repositories.campaign, campaignId);
    return NextResponse.json(missions);
  } catch (error) {
    console.error(error);
    const message = error instanceof Error ? error.message : "Error al obtener misiones";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}

/**
 * POST /api/campaign/[id]/missions
 * Adds a new mission to a campaign
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const campaignId = (await params).id;
    const body = await req.json();
    
    // Validate mission data (without id - generated by use case)
    const validatedMission = embeddedMissionSchema.parse(body);
    
    const createdMission = await addMission(
      repositories.campaign,
      campaignId,
      validatedMission
    );
    
    return NextResponse.json(createdMission, { status: 201 });
  } catch (error) {
    console.error(error);
    const message = error instanceof Error ? error.message : "Error al crear misión";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
