import { addNote, getNotes } from "@/application/useCases/campaign";
import { repositories } from "@/infrastructure/config/repositories";
import { embeddedNoteSchema } from "@/infrastructure/adapters/schemas/campaign.schema";
import { NextRequest, NextResponse } from "next/server";

/**
 * GET /api/campaign/[id]/notes
 * Returns all notes for a campaign, sorted newest first.
 */
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const campaignId = (await params).id;
    const notes = await getNotes(repositories.campaign, campaignId);
    return NextResponse.json(notes);
  } catch (error) {
    console.error(error);
    const message = error instanceof Error ? error.message : "Error al obtener notas";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}

/**
 * POST /api/campaign/[id]/notes
 * Adds a new note to a campaign.
 * 
 * Request body: { comment: string, color?: NoteColorType }
 * Response: 201 + EmbeddedNote (with generated id and createdAt)
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const campaignId = (await params).id;
    const body = await req.json();
    
    // Validate note data (without id/createdAt — generated by use case)
    const validatedNote = embeddedNoteSchema.parse(body);
    
    const createdNote = await addNote(
      repositories.campaign,
      campaignId,
      validatedNote
    );
    
    return NextResponse.json(createdNote, { status: 201 });
  } catch (error) {
    console.error(error);
    const message = error instanceof Error ? error.message : "Error al crear nota";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
