import { addSession, getCampaignById } from "@/application/useCases/campaign";
import { repositories } from "@/infrastructure/config/repositories";
import { embeddedSessionSchema } from "@/infrastructure/adapters/schemas/campaign.schema";
import { NextRequest, NextResponse } from "next/server";

/**
 * GET /api/campaign/[id]/sessions
 * Returns all sessions for a campaign
 */
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const campaignId = (await params).id;
    
    const campaign = await getCampaignById(repositories.campaign, campaignId);
    if (!campaign) {
      return NextResponse.json({ error: "Campaña no encontrada" }, { status: 404 });
    }
    
    return NextResponse.json(campaign.sessions);
  } catch (error) {
    console.error(error);
    const message = error instanceof Error ? error.message : "Error al obtener sesiones";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}

/**
 * POST /api/campaign/[id]/sessions
 * Adds a new session to a campaign
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const campaignId = (await params).id;
    const body = await req.json();
    
    // Validate session data (without id and sessionNumber - generated by use case)
    const validatedSession = embeddedSessionSchema.parse(body);
    
    const createdSession = await addSession(
      repositories.campaign,
      campaignId,
      validatedSession
    );
    
    return NextResponse.json(createdSession, { status: 201 });
  } catch (error) {
    console.error(error);
    const message = error instanceof Error ? error.message : "Error al crear sesión";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
